-- Disable RLS on all tables temporarily (for testing)
ALTER TABLE public.workspaces DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.folders DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.sops DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.sop_versions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.sop_folders DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.sop_assignments DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.tags DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.sop_tags DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.approval_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.approval_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.checklists DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.checklist_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments DISABLE ROW LEVEL SECURITY;
